import type { IconSvgElement } from "@hugeicons/react";
import {
  CssFileIcon,
  File01Icon,
  FileAudioIcon,
  FileBracesIcon,
  FileChartColumnIcon,
  FileCodeIcon,
  FileDatabaseIcon,
  FileDiffIcon,
  FileImageIcon,
  FileScriptIcon,
  FileSpreadsheetIcon,
  FileTerminalIcon,
  FileVideoIcon,
  FileZipIcon,
  HtmlFileIcon,
  TextIcon,
} from "@hugeicons/core-free-icons";

const ICON_BY_EXTENSION: Record<string, IconSvgElement> = {
  png: FileImageIcon,
  jpg: FileImageIcon,
  jpeg: FileImageIcon,
  gif: FileImageIcon,
  webp: FileImageIcon,
  svg: FileImageIcon,
  bmp: FileImageIcon,
  ico: FileImageIcon,
  mp4: FileVideoIcon,
  mkv: FileVideoIcon,
  mov: FileVideoIcon,
  webm: FileVideoIcon,
  avi: FileVideoIcon,
  mp3: FileAudioIcon,
  wav: FileAudioIcon,
  flac: FileAudioIcon,
  ogg: FileAudioIcon,
  m4a: FileAudioIcon,
  zip: FileZipIcon,
  rar: FileZipIcon,
  "7z": FileZipIcon,
  tar: FileZipIcon,
  gz: FileZipIcon,
  bz2: FileZipIcon,
  xz: FileZipIcon,
  ts: FileCodeIcon,
  tsx: FileCodeIcon,
  js: FileCodeIcon,
  jsx: FileCodeIcon,
  mjs: FileCodeIcon,
  cjs: FileCodeIcon,
  json: FileBracesIcon,
  jsonc: FileBracesIcon,
  yaml: FileBracesIcon,
  yml: FileBracesIcon,
  toml: FileBracesIcon,
  xml: FileBracesIcon,
  csv: FileSpreadsheetIcon,
  tsv: FileSpreadsheetIcon,
  xlsx: FileSpreadsheetIcon,
  sql: FileDatabaseIcon,
  db: FileDatabaseIcon,
  sqlite: FileDatabaseIcon,
  py: FileCodeIcon,
  rs: FileCodeIcon,
  go: FileCodeIcon,
  java: FileCodeIcon,
  kt: FileCodeIcon,
  swift: FileCodeIcon,
  c: FileCodeIcon,
  h: FileCodeIcon,
  cpp: FileCodeIcon,
  cs: FileCodeIcon,
  rb: FileCodeIcon,
  php: FileCodeIcon,
  css: CssFileIcon,
  scss: CssFileIcon,
  html: HtmlFileIcon,
  htm: HtmlFileIcon,
  sh: FileTerminalIcon,
  bash: FileTerminalIcon,
  zsh: FileTerminalIcon,
  fish: FileTerminalIcon,
  ps1: FileTerminalIcon,
  bat: FileTerminalIcon,
  cmd: FileTerminalIcon,
  md: TextIcon,
  mdx: TextIcon,
  markdown: TextIcon,
  txt: TextIcon,
  text: TextIcon,
  rst: TextIcon,
  adoc: TextIcon,
  log: TextIcon,
  diff: FileDiffIcon,
  patch: FileDiffIcon,
  lock: FileCodeIcon,
  env: FileScriptIcon,
  ini: FileScriptIcon,
  cfg: FileScriptIcon,
  conf: FileScriptIcon,
  metrics: FileChartColumnIcon,
};

const FALLBACK_ICON = File01Icon;

export function fileIconForPath(path: string): IconSvgElement {
  const name = path.split("/").at(-1) ?? path;
  const dotIndex = name.lastIndexOf(".");
  if (dotIndex <= 0) return FALLBACK_ICON;
  const extension = name.slice(dotIndex + 1).toLowerCase();
  return ICON_BY_EXTENSION[extension] ?? FALLBACK_ICON;
}
